language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install: composer update --no-suggest --no-progress --no-scripts
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
after_success: travis_retry php vendor/bin/php-coveralls